export const salons = [
  {
    id: "temple-paris",
    name: "Les Temples - Paris",
    slug: "temple-paris",
    city: "Paris",
    address: "123 Rue de la Paix, 75000 Paris",
    phone: "+33 1 23 45 67 89",
    description: "Sanctuary of relaxation in the heart of Paris",
    image: "/luxury-spa-paris.jpg",
    hours: {
      monday: { open: "10:00", close: "20:00" },
      tuesday: { open: "10:00", close: "20:00" },
      wednesday: { open: "10:00", close: "20:00" },
      thursday: { open: "10:00", close: "20:00" },
      friday: { open: "10:00", close: "21:00" },
      saturday: { open: "09:00", close: "21:00" },
      sunday: { open: "10:00", close: "19:00" },
    },
  },
  {
    id: "temple-lyon",
    name: "Les Temples - Lyon",
    slug: "temple-lyon",
    city: "Lyon",
    address: "456 Avenue de la République, 69000 Lyon",
    phone: "+33 4 72 34 56 78",
    description: "Wellness retreat in the vibrant city of Lyon",
    image: "/luxury-spa-lyon.jpg",
    hours: {
      monday: { open: "10:00", close: "20:00" },
      tuesday: { open: "10:00", close: "20:00" },
      wednesday: { open: "10:00", close: "20:00" },
      thursday: { open: "10:00", close: "20:00" },
      friday: { open: "10:00", close: "21:00" },
      saturday: { open: "09:00", close: "21:00" },
      sunday: { open: "10:00", close: "19:00" },
    },
  },
  {
    id: "temple-marseille",
    name: "Les Temples - Marseille",
    slug: "temple-marseille",
    city: "Marseille",
    address: "789 Boulevard de la Corniche, 13000 Marseille",
    phone: "+33 4 91 23 45 67",
    description: "Mediterranean escape with sea views",
    image: "/luxury-spa-marseille.jpg",
    hours: {
      monday: { open: "10:00", close: "20:00" },
      tuesday: { open: "10:00", close: "20:00" },
      wednesday: { open: "10:00", close: "20:00" },
      thursday: { open: "10:00", close: "20:00" },
      friday: { open: "10:00", close: "21:00" },
      saturday: { open: "09:00", close: "21:00" },
      sunday: { open: "10:00", close: "19:00" },
    },
  },
]

export const services = [
  {
    id: "massage-relaxant",
    name: "Massage Relaxant",
    description: "Soothing full-body massage to release tension",
    duration: 60,
    price: 89,
    category: "Détente",
    image: "/relaxation-massage.jpg",
  },
  {
    id: "massage-pierres-chaudes",
    name: "Massage aux Pierres Chaudes",
    description: "Therapeutic massage with heated stones",
    duration: 75,
    price: 109,
    category: "Thérapeutique",
    image: "/hot-stone-massage.png",
  },
  {
    id: "massage-sportif",
    name: "Massage Sportif",
    description: "Deep tissue massage for athletes",
    duration: 60,
    price: 99,
    category: "Sportif",
    image: "/sports-massage.jpg",
  },
  {
    id: "massage-facial",
    name: "Soin du Visage Premium",
    description: "Luxurious facial treatment with organic products",
    duration: 45,
    price: 79,
    category: "Détente",
    image: "/facial-spa-treatment.jpg",
  },
  {
    id: "massage-duo",
    name: "Massage en Duo",
    description: "Couples massage experience",
    duration: 60,
    price: 179,
    category: "Détente",
    image: "/couples-massage-spa.jpg",
  },
]

export const employees = [
  {
    id: "emp-1",
    name: "Sophie Martin",
    role: "Masseur",
    salonId: "temple-paris",
    photo: "/professional-woman-diverse.png",
    specialties: ["massage-relaxant", "massage-pierres-chaudes", "massage-facial"],
  },
  {
    id: "emp-2",
    name: "Jean Dupont",
    role: "Masseur",
    salonId: "temple-paris",
    photo: "/professional-man.jpg",
    specialties: ["massage-sportif", "massage-relaxant"],
  },
  {
    id: "emp-3",
    name: "Marie Leclerc",
    role: "Masseur",
    salonId: "temple-lyon",
    photo: "/professional-woman-diverse.png",
    specialties: ["massage-relaxant", "massage-duo", "massage-facial"],
  },
  {
    id: "emp-4",
    name: "Pierre Rousseau",
    role: "Masseur",
    salonId: "temple-marseille",
    photo: "/professional-man.jpg",
    specialties: ["massage-sportif", "massage-pierres-chaudes"],
  },
]

export const appointments = [
  {
    id: "apt-1",
    salonId: "temple-paris",
    employeeId: "emp-1",
    serviceId: "massage-relaxant",
    clientName: "Alice Dupont",
    clientPhone: "+33 6 12 34 56 78",
    clientEmail: "alice@example.com",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    time: "14:00",
    status: "confirmed",
    notes: "First time client, prefers quiet environment",
  },
  {
    id: "apt-2",
    salonId: "temple-paris",
    employeeId: "emp-2",
    serviceId: "massage-sportif",
    clientName: "Marc Leblanc",
    clientPhone: "+33 6 98 76 54 32",
    clientEmail: "marc@example.com",
    date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    time: "10:00",
    status: "confirmed",
    notes: "",
  },
]

export const clients = [
  {
    id: "client-1",
    name: "Alice Dupont",
    phone: "+33 6 12 34 56 78",
    email: "alice@example.com",
    totalSpent: 89,
    visitCount: 1,
    lastVisit: new Date(Date.now() - 86400000).toISOString(),
    notes: "Prefers quiet environment",
  },
  {
    id: "client-2",
    name: "Marc Leblanc",
    phone: "+33 6 98 76 54 32",
    email: "marc@example.com",
    totalSpent: 297,
    visitCount: 3,
    lastVisit: new Date(Date.now() - 604800000).toISOString(),
    notes: "Regular client, athlete",
  },
]
